# Nav2 Global Planner Configuration for Humanoid Robots
# Configuration for path planning algorithms optimized for humanoid locomotion

planner_server:
  ros__parameters:
    # Global planner plugins
    planner_plugins: ["GridBased"]

    # Grid-based planner configuration (Navfn)
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"

      # Planner-specific parameters
      tolerance: 0.5          # Tolerance for goal position (m) - increased for humanoid stability
      use_astar: false        # Use A* instead of Dijkstra's algorithm
      allow_unknown: true     # Allow planning through unknown space

      # Humanoid-specific parameters
      cost_factor: 3.0        # Factor to weight costmap values (higher = more obstacle avoidance)
      neutral_cost: 66        # Neutral cost value for free space (0-254)

      # Performance parameters
      publish_period: 0.5     # Time between path publications (s)

    # Alternative global planner: Global Planner (A*)
    GlobalPlanner:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.5
      use_astar: true         # Use A* algorithm for faster planning
      allow_unknown: true
      cost_factor: 3.0
      neutral_cost: 66
      publish_period: 0.5

    # Alternative: Smac Planner (2D) - for smoother paths
    SmacPlanner:
      plugin: "nav2_smac_planner::SmacPlanner2D"
      tolerance: 0.5          # Tolerance for goal position (m)
      downsample_costmap: false  # Whether to downsample the costmap
      downsampling_factor: 1     # Factor to downsample the costmap resolution
      allow_unknown: true        # Allow planning through unknown space
      max_iterations: 1000000    # Maximum number of iterations to perform
      max_on_approach_iterations: 1000  # Maximum number of iterations after approaching goal
      motion_model_for_search: "8",     # Motion model to use for search
      cost_penalty: 2.0              # Penalty to apply to costmap values
      cache_obstacles: true          # Cache obstacles between iterations
      allow_approach_place_cost: true  # Allow approach at place-cost locations
      smooth_path: true              # Apply smoothing to path

    # Alternative: RRT* Planner for complex environments
    RRTStarPlanner:
      plugin: "nav2_rrt_planner::RRTStarPlanner"
      tolerance: 0.5
      max_iterations: 10000
      max_planning_time: 5.0
      use_initial_guess: true
      number_of_iterations: 1000
      rrt_connect: false
      bidirectional_rrt: true
      sample_rejection_enabled: true
      goal_bias: 0.05
      max_distance_bias: 1.0
      max_distance_ratio: 0.1
      smooth: true
      smooth_iterations: 100
      smooth_path: true

# Planner server general parameters
planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True

# Additional planner parameters for humanoid-specific navigation
humanoid_planner_params:
  ros__parameters:
    # Path optimization parameters for humanoid gait
    path_smoothing: true
    path_smoothing_iterations: 10
    path_smoothing_window_size: 5

    # Humanoid-specific constraints
    min_turning_radius: 0.3   # Minimum turning radius for humanoid (m)
    max_path_length_factor: 3.0  # Maximum path length relative to direct distance
    preferred_path_width: 0.6     # Preferred width for path planning (m)

    # Safety margins for humanoid navigation
    safety_margin_linear: 0.3     # Additional safety margin in linear direction (m)
    safety_margin_angular: 0.2    # Additional safety margin for angular movement (m)

    # Path following parameters
    path_resolution: 0.1          # Resolution of the path points (m)
    goal_distance_tolerance: 0.4  # Tolerance for reaching goal (m) - increased for humanoid
    goal_angle_tolerance: 0.3     # Tolerance for goal orientation (rad)

    # Dynamic obstacle considerations
    dynamic_obstacle_buffer: 0.5  # Buffer for dynamic obstacles (m)
    prediction_horizon: 2.0       # Time horizon for dynamic obstacle prediction (s)

# Path validation parameters
path_validator:
  ros__parameters:
    # Parameters for validating path feasibility for humanoid
    max_linear_velocity: 0.3      # Maximum linear velocity (m/s) - limited for humanoid
    max_angular_velocity: 0.5     # Maximum angular velocity (rad/s) - limited for humanoid
    max_linear_acceleration: 0.2  # Maximum linear acceleration (m/s^2)
    max_angular_acceleration: 0.3 # Maximum angular acceleration (rad/s^2)

    # Footstep planning considerations
    min_step_distance: 0.1        # Minimum distance between footsteps (m)
    max_step_distance: 0.6        # Maximum distance between footsteps (m)
    step_height_threshold: 0.05   # Maximum step height humanoid can handle (m)

    # Stability constraints
    z_threshold: 0.1              # Maximum height change allowed (m)
    pitch_threshold: 0.2          # Maximum pitch angle allowed (rad)
    roll_threshold: 0.2           # Maximum roll angle allowed (rad)

# Recovery behavior parameters for global planning
recovery_planner:
  ros__parameters:
    # Parameters for planning recovery paths when primary plan fails
    recovery_tolerance_increase: 0.5  # Amount to increase tolerance during recovery
    max_recovery_attempts: 3          # Maximum recovery attempts
    recovery_planner_type: "GridBased"  # Planner to use for recovery
    recovery_min_distance: 0.5        # Minimum distance to move during recovery (m)

# Multi-goal planning parameters
multi_goal_planner:
  ros__parameters:
    # Parameters for planning paths with multiple goals
    enable_multi_goal: false          # Enable multi-goal planning
    goal_sequence_timeout: 30.0       # Timeout for goal sequence (s)
    inter_goal_distance: 1.0          # Minimum distance between consecutive goals (m)
    optimize_goal_order: true         # Optimize order of goals to minimize total path length