import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for ROS 2 Humanoid Robotics content
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'intro',
        'setup-ros2',
      ],
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'module-1-ros2/introduction',
        'module-1-ros2/ros2-architecture',
        'module-1-ros2/nodes-topics-services-actions',
        'module-1-ros2/python-integration',
        'module-1-ros2/urdf-modeling',
        'module-1-ros2/launch-files',
        'module-1-ros2/architecture-sketch',
        'module-1-ros2/practical-examples',
        'module-1-ros2/quickstart-guide',
        'module-1-ros2/final-validation-and-summary',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        'module-2-digital-twin/intro',
        'module-2-digital-twin/humanoid-model-configuration',
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        'tutorials/ai-agent-ros2-bridge',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
      items: [
        'module-3-isaac-ai-brain/introduction',
        'module-3-isaac-ai-brain/isaac-platform-overview',
        'module-3-isaac-ai-brain/isaac-sim-setup',
        'module-3-isaac-ai-brain/perception-pipelines',
        'module-3-isaac-ai-brain/navigation-intelligence',
        'module-3-isaac-ai-brain/learning-based-control',
        'module-3-isaac-ai-brain/sim-to-real-transfer',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'module-4-vla/introduction',
        'module-4-vla/vla-foundations',
        'module-4-vla/voice-language-processing',
        'module-4-vla/cognitive-planning',
        'module-4-vla/vision-grounding',
        'module-4-vla/action-execution',
        'module-4-vla/safety-reliability',
        'module-4-vla/capstone-architecture',
        'module-4-vla/end-to-end-pipeline',
        'module-4-vla/quickstart-guide',
      ],
    },
  ],
  module2Sidebar: [
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        'module-2-digital-twin/intro',
        'module-2-digital-twin/humanoid-model-configuration',
      ],
    },
  ],
  module3Sidebar: [
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
      items: [
        'module-3-isaac-ai-brain/introduction',
        'module-3-isaac-ai-brain/isaac-platform-overview',
        'module-3-isaac-ai-brain/isaac-sim-setup',
        'module-3-isaac-ai-brain/perception-pipelines',
        'module-3-isaac-ai-brain/navigation-intelligence',
        'module-3-isaac-ai-brain/learning-based-control',
        'module-3-isaac-ai-brain/sim-to-real-transfer',
      ],
    },
  ],
  module4Sidebar: [
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'module-4-vla/introduction',
        'module-4-vla/vla-foundations',
        'module-4-vla/voice-language-processing',
        'module-4-vla/cognitive-planning',
        'module-4-vla/vision-grounding',
        'module-4-vla/action-execution',
        'module-4-vla/safety-reliability',
        'module-4-vla/capstone-architecture',
        'module-4-vla/end-to-end-pipeline',
        'module-4-vla/quickstart-guide',
      ],
    },
  ],
};

export default sidebars;
