import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for ROS 2 Humanoid Robotics content
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'intro',
        'setup-ros2',
      ],
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'module-1-ros2/introduction',
        'module-1-ros2/ros2-architecture',
        'module-1-ros2/nodes-topics-services-actions',
        'module-1-ros2/python-integration',
        'module-1-ros2/urdf-modeling',
        'module-1-ros2/launch-files',
        'module-1-ros2/architecture-sketch',
        'module-1-ros2/practical-examples',
        'module-1-ros2/quickstart-guide',
        'module-1-ros2/final-validation-and-summary',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        'module-2-digital-twin/intro',
        'module-2-digital-twin/humanoid-model-configuration',
      ],
    },
    {
      type: 'category',
      label: 'Tutorials',
      items: [
        'tutorials/ai-agent-ros2-bridge',
      ],
    },
  ],
};

export default sidebars;
